#!/bin/bash
# Senior Architect Recommended Solution

echo "=== Senior AWS Architect Solution ==="
echo ""
echo "ANALYSIS SUMMARY:"
echo "  ✓ Network: Working (connection refused = path exists)"
echo "  ✓ Security Groups: Correctly configured"
echo "  ✓ IP Configuration: Correct (10.0.10.181)"
echo "  ✗ OpenSearch Container: Not running/listening"
echo ""
echo "ROOT CAUSE:"
echo "  OpenSearch container failed to start or not yet initialized"
echo "  Instance created: 2025-12-14T04:19:43 (may still be initializing)"
echo ""
echo "RECOMMENDED ACTION:"
echo ""
echo "Since the instance is very new, you have two options:"
echo ""
echo "OPTION 1: Wait and Monitor (if instance < 5 minutes old)"
echo "  User data script may still be running."
echo "  Wait 2-3 more minutes, then check ECS logs."
echo ""
echo "OPTION 2: Recreate Instance (Most Reliable)"
echo "  This ensures clean state with latest configuration:"
echo ""
echo "  cd envs/dev"
echo "  terraform taint module.opensearch_ec2[0].aws_instance.opensearch"
echo "  terraform apply -var-file=terraform.tfvars"
echo ""
echo "  Then wait 4-5 minutes for:"
echo "    - Instance creation (2 min)"
echo "    - User data execution (2-3 min)"
echo "    - OpenSearch initialization (1-2 min)"
echo ""
echo "VERIFICATION:"
echo "  After 4-5 minutes, check ECS service logs:"
echo "    aws logs tail /ecs/shelfshack-dev --follow"
echo ""
echo "  You should see successful OpenSearch connections instead of errors."
